name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      download-test:
        description: "Run download from hydroweb.next tests"
        require: true
        type: boolean
        default: false


jobs:
  lint-and-test:
    name: Lint & Tests check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade build
          pip install ".[dev]"

      - name: Run Ruff linter
        run: ruff check .

      - name: Run Ruff formatter check
        run: ruff format --check .

      - name: Run tests
        env:
          HYDROWEB_API_KEY: ${{ secrets.HYDROWEB_API_KEY }}
          EODAG__HYDROWEB_NEXT__AUTH__CREDENTIALS__APIKEY: ${{ secrets.EODAG__HYDROWEB_NEXT__AUTH__CREDENTIALS__APIKEY }}
        run: |
          if [ "${{ inputs.download-test }}" = "true" ]; then
            pytest pixcdust/tests --dl --realdata -v -rs --cov=pixcdust --cov-report=term-missing --cov-report=html --cov-report=markdown:coverage.md
          else
            pytest pixcdust/tests --realdata -v -rs --cov=pixcdust --cov-report=term-missing --cov-report=html --cov-report=markdown:coverage.md
          fi
      - name: Coverage summary
        if: always()
        run: |
          echo "## Code coverage" >> "$GITHUB_STEP_SUMMARY"
          cat coverage.md >> "$GITHUB_STEP_SUMMARY"
